### ISSUE TITLE
Error message: Error in sample.int(length(x), size, replace, prob) : invalid first argument

### ISSUE THREAD

**Issue by Mosen111** [stekhoven/missForest#19] opened 2019-11-06 08:00 UTC
Hi
What am I doing wrong here?

x2.imp <- missForest(x2)

x2 is a data frame, all numerical values, with some missing values. I get this error:

Error in sample.int(length(x), size, replace, prob) : 
  invalid first argument

but when I run with the iris dataset as in the tutorial, I get no errors. Would appreciate it if you could clarify the issue for me. cheers

**Comment by sillasgonzaga** [comment] 2019-12-19 17:32
@Mosen111  Why did you close this issue?

**Comment by Mosen111** [comment] 2019-12-20 01:12
I guessed there was no one to answer, so I closed it.

**Comment by HenrikEckermann** [comment] 2020-01-28 14:48
@Mosen111 : Did you find a solution to this problem? f not, It should be reopened.

**Comment by Mosen111** [comment] 2020-02-01 02:24
Hi, I reopened it, but there is no one to answer here.

**Comment by stephematician** [comment] 2020-02-01 05:42
A data.frame of numbers with some missing values should run without error. For example the following code works for me:

```r
v <- rnorm(20)
v[sample(1:20, size=5)] <- NA
x2 <- as.data.frame(matrix(v, nrow=5))
missForest(x2)
```

Try `debug(missForest)` and investigate at what point the code fails, then compare it to what happens when using the `iris` data.

**Comment by Mosen111** [comment] 2020-02-03 23:37
thanks but too technical for me, I have already found alternatives that work smoothly. cheers

**Comment by kkmann** [comment] 2020-03-04 19:01
I think the problem is the way that you check variable types

https://github.com/stekhoven/missForest/blob/92e1f77ee443d203ddae00b72e71b82da92792cc/R/missForest.R#L84-L92

when users specify attributes for their data, everything is interpreted as factor. Why not use is.factor instead?

**Comment by kkmann** [comment] 2020-03-04 19:17
I had a similar issue before, was caused by a sloppy type check in missForest but should be resolved in the development version, should probably go to CRAN though

**Comment by varelasebastian** [comment] 2020-03-23 23:23
same problem...

**Comment by gdente90** [comment] 2020-03-27 11:20
Dear Mosen111, what kind of alternative did you use?
I also have the same problem, and have no idea what to do!

**Comment by joaquinsalas** [comment] 2020-04-12 19:01
In my case, I was computing the difference in days between to date variables, e.g., 
variable = d1 - d2. The result, althought looked integer, was class "difftime". Using 
variable  = as.numeric(variable,  units="days")

made missForest happy. I hope this helps.

**Comment by luciewoellenstein44** [comment] 2021-01-08 15:14
I had the same problem, turned out missForest did not like my datetime class for my date variables. I computed them into numeric (which should be easier for any analysis done on them anyway) and that made the error go away. Hope this helps!

**Comment by christopherball** [comment] 2021-02-12 22:20
Having just run into the same issue, here's the not-so-obvious but simple cause / solution:

I happen to load my data via **read_csv** to take advantage of the tibble type.  This is the actual culprit.  Applying a **as.data.frame()** ahead of the **missForest()** call solved my problem.  Alternatively, you could simply fallback to the old way of loading data via **read.csv()**.

**Comment by WondimuAhmed** [comment] 2022-06-24 17:16
Applying **as.data.frame()** prior to running **missForest**  solved my problem as well.

**Comment by stekhoven** [comment] 2023-02-24 09:52
We intend to move to ranger soon, this will make missForest able to handle tibbles.

**Closed by stekhoven** 2023-02-24 09:52 UTC
Labels: type bug
